### ISSUE TITLE
Add preprocesing for ocean color data

### ISSUE THREAD

**Issue by paramnav** [mardatade/Cabo-Verde-Dust#5]
Use a cron job to extract ocean color data from copernicus

**Comment by willirath** [comment]
Here's how I'd proceed:

- Find the relevant copernicus dataset id (Essentially find a product or a combination of products here https://data.marine.copernicus.eu/products and then click through to "Data Access" and the different product ids. For the near-real time daily gap-free fields, it's `"cmems_obs-oc_glo_bgc-plankton_nrt_l4-gapfree-multi-4km_P1D"`.

- Get Copernicus Credentials. I can add mine to the production env (in a safe way). But for playting with the pre-processing, you'll need an account with: https://marine.copernicus.eu.

- The copernicus client. Installation instructions are here: https://help.marine.copernicus.eu/en/articles/7949409-copernicus-marine-toolbox-introduction Loading a dataset into Xarray is then essentially: `copernicusmarine.open_dataset(dataset_id="<dataset-id>")`

- Decision about the final format: Writing everything to a netCDF file would do. But we might want to use Zarr, because it works better in a cloud context. We can decide about this later, though.

**Comment by willirath** [comment]
Closed in #7
